<a href="https://colab.research.google.com/github/PratikMindhe/Internship/blob/main/Task_1/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#using numpy sample program no 1
#program for print two dimensional array
import numpy as np
a= np.array([[7,8,9],[5,6,7]])
print(a)

[[7 8 9]
 [5 6 7]]


In [2]:
#using numpy sample program no 2
#program for adding two dimensional array
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[5,8,7],
            [9,3,5]])
c=a+b
print(c)

[[ 6 10 10]
 [13  8 11]]


In [3]:
#using numpy smaple program no 3
# program for arange numbers using numpy arange function 
import numpy as np
a=np.arange(4)
print(a)


[0 1 2 3]


In [4]:
#program for to create an array of the number 1 to 50
import numpy as np
arr=np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
